'''
Auto Generated by my2ca
@author: sam
Generated on 2011-12-15
'''

import pycassa

'''
Please use another mechanism to handle these data
'''
keyspace = "test"
servers = ['localhost:9960',]

credentials = "testuser:nopass"

"""
The Connection Pool
"""
connection_pool = pycassa.connect(keyspace=keyspace, servers=servers, credentials=credentials)

