'''
Auto Generated by my2ca
@author: 
Generated on 
'''

import pycassa

'''
Please use another mechanism to handle these data
'''
keyspace = ""
servers = []
credentials = None

connection_pool = pycassa.connect(keyspace=keyspace, servers=servers, credentials=credentials)