'''
Auto Generated by my2ca
@author: ${author}
Generated on ${date}
'''

import pycassa

'''
Please use another mechanism to handle these data
'''
keyspace = "${keyspace}"
% if servers:
servers = ${servers}
% else:
servers = ['localhost:9960',]
% endif

% if credentials:
credentials = ${credentials}
% else:
credentials = "testuser:nopass"
% endif

"""
The Connection Pool
"""
connection_pool = pycassa.connect(keyspace=keyspace, servers=servers, credentials=credentials)

