'''
Auto Generated by my2ca
@author: ${author}
Generated on ${date}
'''

import pycassa

'''
Please use another mechanism to handle these data
'''
keyspace = "${keyspace}"
servers = ${servers}
credentials = ${credentials}

"""
The Connection Pool
"""
connection_pool = pycassa.connect(keyspace=keyspace, servers=servers, credentials=credentials)

